server:
  port: 80

spring:
  application:
    name: MySpringboootApplication
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&useSSL=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: root
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 100
    database: 1
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl