server:
  port: 80

spring:
  application:
    name: MySpringboootApplication
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/haowanba?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      username: root
      password:
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 100
    database: 1
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl